# Configuración para PostgreSQL

spring:
  devtools:
    livereload:
      enabled: true
  profiles:
    active: db-h2
  logging:
    level:
      org:
        springframework:
          validation: DEBUG
        hibernate:
          validator: DEBUG

  pantheon:
    security:
      local:
        path-source: mock-user.json
        test: true