# Configuración para PostgreSQL
logging:
  level:
    root: TRACE

spring:
  devtools:
    livereload:
      enabled: true
  profiles:
    active: db-h2

  security:
    oauth2:
      client:
        registration:
          pantheon:
            clientId: "oidc-client"
            clientSecret: "secret"
            authorization-grant-type: "authorization_code"
            redirect-uri: http://localhost:8080/login/oauth2/code/oidc-client
        provider:
          pantheon:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            #user-info-uri: http://localhost:9000/userinfo
            #user-name-attribute: sub

