spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: login-client
            client-id: login-client
            client-secret: openid-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/login-client
            scope: openid,profile
            client-name: login-client
        provider:
          login-client:
            authorization-uri: http://localhost:9090/oauth2/authorize
            token-uri: http://localhost:9090/oauth2/token
            jwk-set-uri: http://localhost:9090/oauth2/jwks