# Configuración para PostgreSQL

spring:
  devtools:
    livereload:
      enabled: true
  profiles:
    active: db-h2, authorization-oauth2
  pantheon:
    security:
      local:
        path-source: mock-user.json
        test: false
logging:
  level:
    root: trace