spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/management
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql